using System.Numerics;
using System.Security.Cryptography;

namespace DeskBox.Services.Plugins;

/// <summary>
/// Ed25519 signature VERIFICATION (public keys only - plugin packages and
/// the dev tooling sign elsewhere). Implemented with BigInteger over the
/// textbook RFC 8032 formulas because the .NET 10 BCL ships no Ed25519
/// (post-quantum algorithms made it in; Ed25519 did not), and a dependency
/// free implementation avoids dragging a NuGet package through the Native
/// AOT audit pipeline. Verification processes public data only, so
/// non-constant-time arithmetic is acceptable - constant time protects
/// SIGNING keys, which never live in the host.
/// Validated against vectors generated by the Node tooling
/// (scripts/spike) and against the committed spike package signatures
/// (cross-implementation proof: C# verifies Node-signed bytes).
/// </summary>
internal static class PluginEd25519
{
    private static readonly BigInteger P = BigInteger.Pow(2, 255) - 19;
    private static readonly BigInteger L = BigInteger.Parse("7237005577332262213973186563042994240857116359379907606001950938285454250989");
    private static readonly BigInteger D = Mod(BigInteger.Parse("-121665") * BigInteger.ModPow(121666, P - 2, P), P);
    private static readonly BigInteger SqrtM1 = BigInteger.ModPow(2, (P - 1) / 4, P);

    // Ed25519 base point (RFC 8032 §5.1).
    private static readonly BigInteger BaseX = BigInteger.Parse("15112221349535400772501151409588531511454012693041857206046113283949847762202");
    private static readonly BigInteger BaseY = BigInteger.Parse("46316835694926478169428394003475163141307993866256225615783033603165251855960");

    /// <summary>Verifies a 64-byte signature over the message with the 32-byte raw public key.</summary>
    public static bool Verify(ReadOnlySpan<byte> signature, ReadOnlySpan<byte> message, ReadOnlySpan<byte> publicKey)
    {
        if (signature.Length != 64 || publicKey.Length != 32)
        {
            return false;
        }

        // S = second half, as a little-endian scalar; reject 0 and >= L
        // (malleability discipline - the spike tooling never produces these).
        BigInteger s = ReadLittleEndian(signature[32..64]);
        if (s.Sign == 0 || s >= L)
        {
            return false;
        }

        // Strict decoding (round 9): non-canonical encodings and
        // small-order points are rejected for BOTH the public key and R.
        // Without this, a malicious publisherPublicKey (e.g. the identity
        // point) makes h*A collapse, and forged signatures verify for any
        // message with no private key at all.
        if (!TryDecodeStrict(publicKey, out EdwardsPoint a))
        {
            return false;
        }
        if (!TryDecodeStrict(signature[..32], out EdwardsPoint r))
        {
            return false;
        }

        // h = SHA512(R || A || M) mod L
        byte[] hashInput = new byte[32 + 32 + message.Length];
        signature[..32].CopyTo(hashInput);
        publicKey.CopyTo(hashInput.AsSpan(32));
        message.CopyTo(hashInput.AsSpan(64));
        BigInteger h = ReadLittleEndian(SHA512.HashData(hashInput)) % L;

        // Signing law: s·B = R + h·A (s = r + h·a). Verify by comparing
        // the encodings of both sides.
        EdwardsPoint left = ScalarMult(Base(), s);
        EdwardsPoint right = Add(r, ScalarMult(a, h));
        Span<byte> leftEncoded = stackalloc byte[32];
        Span<byte> rightEncoded = stackalloc byte[32];
        left.Encode(leftEncoded);
        right.Encode(rightEncoded);
        return leftEncoded.SequenceEqual(rightEncoded);
    }

    /// <summary>
    /// Strict point decoding: canonical encoding only (the re-encoded
    /// point must be byte-identical, which also rejects y >= p and unused
    /// high bits), and the point must NOT be in the 8-torsion subgroup
    /// ([8]P = identity) - the small-order set used by weak-key forges.
    /// </summary>
    private static bool TryDecodeStrict(ReadOnlySpan<byte> encoded, out EdwardsPoint point)
    {
        if (!TryDecompress(encoded, out point))
        {
            return false;
        }
        Span<byte> canonical = stackalloc byte[32];
        point.Encode(canonical);
        if (!canonical.SequenceEqual(encoded))
        {
            return false;
        }
        EdwardsPoint p2 = Add(point, point);
        EdwardsPoint p4 = Add(p2, p2);
        EdwardsPoint p8 = Add(p4, p4);
        return !IsIdentity(p8);
    }

    private static bool IsIdentity(EdwardsPoint point)
    {
        // Projective identity: X = 0, Y = Z (any Z != 0).
        return point.X.IsZero && point.Y == point.Z;
    }

    private readonly struct EdwardsPoint(BigInteger x, BigInteger y, BigInteger z, BigInteger t)
    {
        public BigInteger X { get; } = Mod(x, P);
        public BigInteger Y { get; } = Mod(y, P);
        public BigInteger Z { get; } = Mod(z, P);
        public BigInteger T { get; } = Mod(t, P);
    }

    private static EdwardsPoint Base() => new(BaseX, BaseY, 1, Mod(BaseX * BaseY, P));

    // Unified addition in extended coordinates (RFC 8032 §5.1.4); doubling
    // reuses it (P + P is valid for the unified formula).
    private static EdwardsPoint Add(EdwardsPoint p1, EdwardsPoint p2)
    {
        BigInteger a = Mod((p1.Y - p1.X) * (p2.Y - p2.X), P);
        BigInteger b = Mod((p1.Y + p1.X) * (p2.Y + p2.X), P);
        BigInteger c = Mod(2 * D * p1.T * p2.T, P);
        BigInteger d = Mod(2 * p1.Z * p2.Z, P);
        BigInteger e = b - a;
        BigInteger f = d - c;
        BigInteger g = d + c;
        BigInteger h = b + a;
        return new EdwardsPoint(
            Mod(e * f, P),
            Mod(g * h, P),
            Mod(f * g, P),
            Mod(e * h, P));
    }

    private static EdwardsPoint ScalarMult(EdwardsPoint point, BigInteger scalar)
    {
        var result = new EdwardsPoint(0, 1, 1, 0); // neutral element
        EdwardsPoint addend = point;
        scalar = Mod(scalar, L);
        while (scalar.Sign > 0)
        {
            if (!scalar.IsEven)
            {
                result = Add(result, addend);
            }
            addend = Add(addend, addend);
            scalar >>= 1;
        }
        return result;
    }

    private static bool TryDecompress(ReadOnlySpan<byte> encoded, out EdwardsPoint point)
    {
        bool xIsNegative = (encoded[31] & 0x80) != 0;
        BigInteger y = ReadLittleEndian(encoded) & (BigInteger.Pow(2, 255) - 1);
        if (y >= P)
        {
            point = default;
            return false;
        }

        // x² = (y² - 1) / (d·y² + 1); recover via RFC 8032 §5.1.3:
        // x = u·v³·(u·v⁷)^((p-5)/8), then fix up with sqrt(-1) if needed.
        BigInteger y2 = Mod(y * y, P);
        BigInteger u = Mod(y2 - 1, P);
        BigInteger v = Mod(D * y2 + 1, P);
        BigInteger x = Mod(u * Mod(v * v * v, P) * BigInteger.ModPow(Mod(u * BigInteger.ModPow(v, 7, P), P), (P - 5) / 8, P), P);
        BigInteger vx2 = Mod(v * x * x, P);
        if (Mod(vx2 - u, P) != 0)
        {
            x = Mod(x * SqrtM1, P);
            vx2 = Mod(v * x * x, P);
            if (Mod(vx2 - u, P) != 0)
            {
                point = default;
                return false;
            }
        }
        if (x.Sign == 0 && xIsNegative)
        {
            point = default;
            return false; // sign bit set on x = 0 is not a canonical encoding
        }
        if (x.IsEven == xIsNegative)
        {
            x = Mod(P - x, P);
        }
        point = new EdwardsPoint(x, y, 1, Mod(x * y, P));
        return true;
    }

    private static void Encode(this EdwardsPoint point, Span<byte> destination)
    {
        BigInteger x = Mod(point.X * ModInverse(point.Z), P);
        BigInteger y = Mod(point.Y * ModInverse(point.Z), P);
        bool xIsNegative = !x.IsEven;
        WriteLittleEndian(y, destination);
        if (xIsNegative)
        {
            destination[31] |= 0x80;
        }
    }

    private static BigInteger ModInverse(BigInteger value) => BigInteger.ModPow(Mod(value, P), P - 2, P);

    private static BigInteger Mod(BigInteger value, BigInteger modulus)
    {
        BigInteger remainder = value % modulus;
        return remainder.Sign < 0 ? remainder + modulus : remainder;
    }

    private static BigInteger ReadLittleEndian(ReadOnlySpan<byte> bytes)
    {
        BigInteger value = 0;
        for (int i = bytes.Length - 1; i >= 0; i--)
        {
            value = (value << 8) | bytes[i];
        }
        return value;
    }

    private static void WriteLittleEndian(BigInteger value, Span<byte> destination)
    {
        for (int i = 0; i < destination.Length; i++)
        {
            destination[i] = (byte)(value & 0xFF);
            value >>= 8;
        }
    }
}
