using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Markup;
namespace DeskBox.MusicPackage.Rendering;
public sealed partial class MusicWidgetContent
{
    private readonly List<Action> _detachViewHandlers = [];
    private Grid RootGrid = null!;
    private Grid MinimalLayout = null!;
    private Microsoft.UI.Xaml.Shapes.Rectangle MinimalArtworkImage = null!;
    private Button MinimalPlayPauseButton = null!;
    private Button MinimalNextButton = null!;
    private Grid MinimalTitleMarqueeHost = null!;
    private Microsoft.UI.Xaml.Media.RectangleGeometry MinimalTitleMarqueeClip = null!;
    private TextBlock MinimalTitleStaticText = null!;
    private Canvas MinimalTitleMarqueeCanvas = null!;
    private TextBlock MinimalTitleTextPrimary = null!;
    private TextBlock MinimalTitleTextClone = null!;
    private TextBlock MinimalTitleMeasureText = null!;
    private Button MinimalSourceButton = null!;
    private Grid ContentGrid = null!;
    private ColumnDefinition AlbumColumn = null!;
    private RowDefinition TopRow = null!;
    private Border AlbumArtShadow = null!;
    private Border AlbumArtSurface = null!;
    private Image AlbumArtworkImage = null!;
    private Border AlbumArtInnerBorder = null!;
    private Border AlbumArtPlaceholderBackground = null!;
    private Grid TrackInfoGrid = null!;
    private Grid TitleMarqueeHost = null!;
    private Microsoft.UI.Xaml.Media.RectangleGeometry TitleMarqueeClip = null!;
    private TextBlock TitleStaticText = null!;
    private Canvas TitleMarqueeCanvas = null!;
    private TextBlock TitleTextPrimary = null!;
    private TextBlock TitleTextClone = null!;
    private TextBlock TitleMeasureText = null!;
    private Button SourceButton = null!;
    private Grid ProgressRow = null!;
    private ColumnDefinition PositionColumn = null!;
    private ColumnDefinition DurationColumn = null!;
    private Grid ProgressHost = null!;
    private Border ProgressTrack = null!;
    private Border ProgressFill = null!;
    private Microsoft.UI.Xaml.Shapes.Ellipse ProgressThumb = null!;
    private StackPanel ControlsPanel = null!;
    private Button PlaybackModeButton = null!;
    private Button PreviousButton = null!;
    private Button PlayPauseButton = null!;
    private Button NextButton = null!;
    private Button VolumeButton = null!;
    private Grid RecordLayout = null!;
    private Grid RecordVinylHost = null!;
    private Microsoft.UI.Xaml.Media.RotateTransform RecordVinylRotateTransform = null!;
    private Grid RecordTonearm = null!;
    private TextBlock RecordTitleText = null!;
    private TextBlock RecordArtistText = null!;
    private Button RecordSourceButton = null!;
    private Grid RecordProgressHost = null!;
    private Border RecordProgressTrack = null!;
    private Border RecordProgressFill = null!;
    private StackPanel RecordControlsPanel = null!;
    private Button RecordPlaybackModeButton = null!;
    private Button RecordPreviousButton = null!;
    private Button RecordPlayPauseButton = null!;
    private Button RecordNextButton = null!;
    private Button RecordVolumeButton = null!;
    private Grid RecordHorizontalLayout = null!;
    private Grid RecordHorizontalVinylHost = null!;
    private Microsoft.UI.Xaml.Media.RotateTransform RecordHorizontalVinylRotateTransform = null!;
    private TextBlock RecordHorizontalTitleText = null!;
    private TextBlock RecordHorizontalArtistText = null!;
    private Button RecordHorizontalSourceButton = null!;
    private Grid RecordHorizontalProgressHost = null!;
    private Border RecordHorizontalProgressTrack = null!;
    private Border RecordHorizontalProgressFill = null!;
    private StackPanel RecordHorizontalControlsPanel = null!;
    private Button RecordHorizontalPlaybackModeButton = null!;
    private Button RecordHorizontalPreviousButton = null!;
    private Button RecordHorizontalPlayPauseButton = null!;
    private Button RecordHorizontalNextButton = null!;
    private Button RecordHorizontalVolumeButton = null!;
    private Border InlineVolumePanel = null!;
    private Slider InlineSystemVolumeSlider = null!;
    private void InitializeView(string packageRoot)
    {
        var document = (UserControl)XamlReader.Load(File.ReadAllText(
            System.IO.Path.Combine(packageRoot, "music.xaml")));
        Services.PackageLog.Write("[MusicPackage] text XAML loaded");
        Content = document;
        RootGrid = Require<Grid>(document, "RootGrid");
        MinimalLayout = Require<Grid>(document, "MinimalLayout");
        MinimalArtworkImage = Require<Microsoft.UI.Xaml.Shapes.Rectangle>(document, "MinimalArtworkImage");
        MinimalPlayPauseButton = Require<Button>(document, "MinimalPlayPauseButton");
        MinimalNextButton = Require<Button>(document, "MinimalNextButton");
        MinimalTitleMarqueeHost = Require<Grid>(document, "MinimalTitleMarqueeHost");
        MinimalTitleMarqueeClip = Require<Microsoft.UI.Xaml.Media.RectangleGeometry>(document, "MinimalTitleMarqueeClip");
        MinimalTitleStaticText = Require<TextBlock>(document, "MinimalTitleStaticText");
        MinimalTitleMarqueeCanvas = Require<Canvas>(document, "MinimalTitleMarqueeCanvas");
        MinimalTitleTextPrimary = Require<TextBlock>(document, "MinimalTitleTextPrimary");
        MinimalTitleTextClone = Require<TextBlock>(document, "MinimalTitleTextClone");
        MinimalTitleMeasureText = Require<TextBlock>(document, "MinimalTitleMeasureText");
        MinimalSourceButton = Require<Button>(document, "MinimalSourceButton");
        ContentGrid = Require<Grid>(document, "ContentGrid");
        AlbumColumn = Require<ColumnDefinition>(document, "AlbumColumn");
        TopRow = Require<RowDefinition>(document, "TopRow");
        AlbumArtShadow = Require<Border>(document, "AlbumArtShadow");
        AlbumArtSurface = Require<Border>(document, "AlbumArtSurface");
        AlbumArtworkImage = Require<Image>(document, "AlbumArtworkImage");
        AlbumArtInnerBorder = Require<Border>(document, "AlbumArtInnerBorder");
        AlbumArtPlaceholderBackground = Require<Border>(document, "AlbumArtPlaceholderBackground");
        TrackInfoGrid = Require<Grid>(document, "TrackInfoGrid");
        TitleMarqueeHost = Require<Grid>(document, "TitleMarqueeHost");
        TitleMarqueeClip = Require<Microsoft.UI.Xaml.Media.RectangleGeometry>(document, "TitleMarqueeClip");
        TitleStaticText = Require<TextBlock>(document, "TitleStaticText");
        TitleMarqueeCanvas = Require<Canvas>(document, "TitleMarqueeCanvas");
        TitleTextPrimary = Require<TextBlock>(document, "TitleTextPrimary");
        TitleTextClone = Require<TextBlock>(document, "TitleTextClone");
        TitleMeasureText = Require<TextBlock>(document, "TitleMeasureText");
        SourceButton = Require<Button>(document, "SourceButton");
        ProgressRow = Require<Grid>(document, "ProgressRow");
        PositionColumn = Require<ColumnDefinition>(document, "PositionColumn");
        DurationColumn = Require<ColumnDefinition>(document, "DurationColumn");
        ProgressHost = Require<Grid>(document, "ProgressHost");
        ProgressTrack = Require<Border>(document, "ProgressTrack");
        ProgressFill = Require<Border>(document, "ProgressFill");
        ProgressThumb = Require<Microsoft.UI.Xaml.Shapes.Ellipse>(document, "ProgressThumb");
        ControlsPanel = Require<StackPanel>(document, "ControlsPanel");
        PlaybackModeButton = Require<Button>(document, "PlaybackModeButton");
        PreviousButton = Require<Button>(document, "PreviousButton");
        PlayPauseButton = Require<Button>(document, "PlayPauseButton");
        NextButton = Require<Button>(document, "NextButton");
        VolumeButton = Require<Button>(document, "VolumeButton");
        RecordLayout = Require<Grid>(document, "RecordLayout");
        RecordVinylHost = Require<Grid>(document, "RecordVinylHost");
        RecordVinylRotateTransform = Require<Microsoft.UI.Xaml.Media.RotateTransform>(document, "RecordVinylRotateTransform");
        RecordTonearm = Require<Grid>(document, "RecordTonearm");
        RecordTitleText = Require<TextBlock>(document, "RecordTitleText");
        RecordArtistText = Require<TextBlock>(document, "RecordArtistText");
        RecordSourceButton = Require<Button>(document, "RecordSourceButton");
        RecordProgressHost = Require<Grid>(document, "RecordProgressHost");
        RecordProgressTrack = Require<Border>(document, "RecordProgressTrack");
        RecordProgressFill = Require<Border>(document, "RecordProgressFill");
        RecordControlsPanel = Require<StackPanel>(document, "RecordControlsPanel");
        RecordPlaybackModeButton = Require<Button>(document, "RecordPlaybackModeButton");
        RecordPreviousButton = Require<Button>(document, "RecordPreviousButton");
        RecordPlayPauseButton = Require<Button>(document, "RecordPlayPauseButton");
        RecordNextButton = Require<Button>(document, "RecordNextButton");
        RecordVolumeButton = Require<Button>(document, "RecordVolumeButton");
        RecordHorizontalLayout = Require<Grid>(document, "RecordHorizontalLayout");
        RecordHorizontalVinylHost = Require<Grid>(document, "RecordHorizontalVinylHost");
        RecordHorizontalVinylRotateTransform = Require<Microsoft.UI.Xaml.Media.RotateTransform>(document, "RecordHorizontalVinylRotateTransform");
        RecordHorizontalTitleText = Require<TextBlock>(document, "RecordHorizontalTitleText");
        RecordHorizontalArtistText = Require<TextBlock>(document, "RecordHorizontalArtistText");
        RecordHorizontalSourceButton = Require<Button>(document, "RecordHorizontalSourceButton");
        RecordHorizontalProgressHost = Require<Grid>(document, "RecordHorizontalProgressHost");
        RecordHorizontalProgressTrack = Require<Border>(document, "RecordHorizontalProgressTrack");
        RecordHorizontalProgressFill = Require<Border>(document, "RecordHorizontalProgressFill");
        RecordHorizontalControlsPanel = Require<StackPanel>(document, "RecordHorizontalControlsPanel");
        RecordHorizontalPlaybackModeButton = Require<Button>(document, "RecordHorizontalPlaybackModeButton");
        RecordHorizontalPreviousButton = Require<Button>(document, "RecordHorizontalPreviousButton");
        RecordHorizontalPlayPauseButton = Require<Button>(document, "RecordHorizontalPlayPauseButton");
        RecordHorizontalNextButton = Require<Button>(document, "RecordHorizontalNextButton");
        RecordHorizontalVolumeButton = Require<Button>(document, "RecordHorizontalVolumeButton");
        InlineVolumePanel = Require<Border>(document, "InlineVolumePanel");
        InlineSystemVolumeSlider = Require<Slider>(document, "InlineSystemVolumeSlider");
        Microsoft.UI.Xaml.RoutedEventHandler handler0 = (sender, args) => Services.MusicUiContext.Invoke(() => PlayPauseButton_Click(sender, args));
        MinimalPlayPauseButton.Click += handler0;
        _detachViewHandlers.Add(() => MinimalPlayPauseButton.Click -= handler0);
        Microsoft.UI.Xaml.RoutedEventHandler handler1 = (sender, args) => Services.MusicUiContext.Invoke(() => NextButton_Click(sender, args));
        MinimalNextButton.Click += handler1;
        _detachViewHandlers.Add(() => MinimalNextButton.Click -= handler1);
        Microsoft.UI.Xaml.SizeChangedEventHandler handler2 = (sender, args) => Services.MusicUiContext.Invoke(() => TitleMarqueeHost_SizeChanged(sender, args));
        MinimalTitleMarqueeHost.SizeChanged += handler2;
        _detachViewHandlers.Add(() => MinimalTitleMarqueeHost.SizeChanged -= handler2);
        Microsoft.UI.Xaml.RoutedEventHandler handler3 = (sender, args) => Services.MusicUiContext.Invoke(() => SourceButton_Click(sender, args));
        MinimalSourceButton.Click += handler3;
        _detachViewHandlers.Add(() => MinimalSourceButton.Click -= handler3);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler4 = (sender, args) => Services.MusicUiContext.Invoke(() => AlbumArtSurface_PointerEntered(sender, args));
        AlbumArtSurface.PointerEntered += handler4;
        _detachViewHandlers.Add(() => AlbumArtSurface.PointerEntered -= handler4);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler5 = (sender, args) => Services.MusicUiContext.Invoke(() => AlbumArtSurface_PointerExited(sender, args));
        AlbumArtSurface.PointerExited += handler5;
        _detachViewHandlers.Add(() => AlbumArtSurface.PointerExited -= handler5);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler6 = (sender, args) => Services.MusicUiContext.Invoke(() => AlbumArtSurface_PointerMoved(sender, args));
        AlbumArtSurface.PointerMoved += handler6;
        _detachViewHandlers.Add(() => AlbumArtSurface.PointerMoved -= handler6);
        Microsoft.UI.Xaml.SizeChangedEventHandler handler7 = (sender, args) => Services.MusicUiContext.Invoke(() => AlbumArtSurface_SizeChanged(sender, args));
        AlbumArtSurface.SizeChanged += handler7;
        _detachViewHandlers.Add(() => AlbumArtSurface.SizeChanged -= handler7);
        Microsoft.UI.Xaml.SizeChangedEventHandler handler8 = (sender, args) => Services.MusicUiContext.Invoke(() => TitleMarqueeHost_SizeChanged(sender, args));
        TitleMarqueeHost.SizeChanged += handler8;
        _detachViewHandlers.Add(() => TitleMarqueeHost.SizeChanged -= handler8);
        Microsoft.UI.Xaml.RoutedEventHandler handler9 = (sender, args) => Services.MusicUiContext.Invoke(() => SourceButton_Click(sender, args));
        SourceButton.Click += handler9;
        _detachViewHandlers.Add(() => SourceButton.Click -= handler9);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler10 = (sender, args) => Services.MusicUiContext.Invoke(() => ProgressHost_PointerEntered(sender, args));
        ProgressHost.PointerEntered += handler10;
        _detachViewHandlers.Add(() => ProgressHost.PointerEntered -= handler10);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler11 = (sender, args) => Services.MusicUiContext.Invoke(() => ProgressHost_PointerExited(sender, args));
        ProgressHost.PointerExited += handler11;
        _detachViewHandlers.Add(() => ProgressHost.PointerExited -= handler11);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler12 = (sender, args) => Services.MusicUiContext.Invoke(() => ProgressHost_PointerMoved(sender, args));
        ProgressHost.PointerMoved += handler12;
        _detachViewHandlers.Add(() => ProgressHost.PointerMoved -= handler12);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler13 = (sender, args) => Services.MusicUiContext.Invoke(() => ProgressHost_PointerPressed(sender, args));
        ProgressHost.PointerPressed += handler13;
        _detachViewHandlers.Add(() => ProgressHost.PointerPressed -= handler13);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler14 = (sender, args) => Services.MusicUiContext.Invoke(() => ProgressHost_PointerReleased(sender, args));
        ProgressHost.PointerReleased += handler14;
        _detachViewHandlers.Add(() => ProgressHost.PointerReleased -= handler14);
        Microsoft.UI.Xaml.RoutedEventHandler handler15 = (sender, args) => Services.MusicUiContext.Invoke(() => PlaybackModeButton_Click(sender, args));
        PlaybackModeButton.Click += handler15;
        _detachViewHandlers.Add(() => PlaybackModeButton.Click -= handler15);
        Microsoft.UI.Xaml.RoutedEventHandler handler16 = (sender, args) => Services.MusicUiContext.Invoke(() => PreviousButton_Click(sender, args));
        PreviousButton.Click += handler16;
        _detachViewHandlers.Add(() => PreviousButton.Click -= handler16);
        Microsoft.UI.Xaml.RoutedEventHandler handler17 = (sender, args) => Services.MusicUiContext.Invoke(() => PlayPauseButton_Click(sender, args));
        PlayPauseButton.Click += handler17;
        _detachViewHandlers.Add(() => PlayPauseButton.Click -= handler17);
        Microsoft.UI.Xaml.RoutedEventHandler handler18 = (sender, args) => Services.MusicUiContext.Invoke(() => NextButton_Click(sender, args));
        NextButton.Click += handler18;
        _detachViewHandlers.Add(() => NextButton.Click -= handler18);
        Microsoft.UI.Xaml.RoutedEventHandler handler19 = (sender, args) => Services.MusicUiContext.Invoke(() => VolumeButton_Click(sender, args));
        VolumeButton.Click += handler19;
        _detachViewHandlers.Add(() => VolumeButton.Click -= handler19);
        Microsoft.UI.Xaml.RoutedEventHandler handler20 = (sender, args) => Services.MusicUiContext.Invoke(() => SourceButton_Click(sender, args));
        RecordSourceButton.Click += handler20;
        _detachViewHandlers.Add(() => RecordSourceButton.Click -= handler20);
        Microsoft.UI.Xaml.RoutedEventHandler handler21 = (sender, args) => Services.MusicUiContext.Invoke(() => PlaybackModeButton_Click(sender, args));
        RecordPlaybackModeButton.Click += handler21;
        _detachViewHandlers.Add(() => RecordPlaybackModeButton.Click -= handler21);
        Microsoft.UI.Xaml.RoutedEventHandler handler22 = (sender, args) => Services.MusicUiContext.Invoke(() => PreviousButton_Click(sender, args));
        RecordPreviousButton.Click += handler22;
        _detachViewHandlers.Add(() => RecordPreviousButton.Click -= handler22);
        Microsoft.UI.Xaml.RoutedEventHandler handler23 = (sender, args) => Services.MusicUiContext.Invoke(() => PlayPauseButton_Click(sender, args));
        RecordPlayPauseButton.Click += handler23;
        _detachViewHandlers.Add(() => RecordPlayPauseButton.Click -= handler23);
        Microsoft.UI.Xaml.RoutedEventHandler handler24 = (sender, args) => Services.MusicUiContext.Invoke(() => NextButton_Click(sender, args));
        RecordNextButton.Click += handler24;
        _detachViewHandlers.Add(() => RecordNextButton.Click -= handler24);
        Microsoft.UI.Xaml.RoutedEventHandler handler25 = (sender, args) => Services.MusicUiContext.Invoke(() => VolumeButton_Click(sender, args));
        RecordVolumeButton.Click += handler25;
        _detachViewHandlers.Add(() => RecordVolumeButton.Click -= handler25);
        Microsoft.UI.Xaml.RoutedEventHandler handler26 = (sender, args) => Services.MusicUiContext.Invoke(() => SourceButton_Click(sender, args));
        RecordHorizontalSourceButton.Click += handler26;
        _detachViewHandlers.Add(() => RecordHorizontalSourceButton.Click -= handler26);
        Microsoft.UI.Xaml.RoutedEventHandler handler27 = (sender, args) => Services.MusicUiContext.Invoke(() => PlaybackModeButton_Click(sender, args));
        RecordHorizontalPlaybackModeButton.Click += handler27;
        _detachViewHandlers.Add(() => RecordHorizontalPlaybackModeButton.Click -= handler27);
        Microsoft.UI.Xaml.RoutedEventHandler handler28 = (sender, args) => Services.MusicUiContext.Invoke(() => PreviousButton_Click(sender, args));
        RecordHorizontalPreviousButton.Click += handler28;
        _detachViewHandlers.Add(() => RecordHorizontalPreviousButton.Click -= handler28);
        Microsoft.UI.Xaml.RoutedEventHandler handler29 = (sender, args) => Services.MusicUiContext.Invoke(() => PlayPauseButton_Click(sender, args));
        RecordHorizontalPlayPauseButton.Click += handler29;
        _detachViewHandlers.Add(() => RecordHorizontalPlayPauseButton.Click -= handler29);
        Microsoft.UI.Xaml.RoutedEventHandler handler30 = (sender, args) => Services.MusicUiContext.Invoke(() => NextButton_Click(sender, args));
        RecordHorizontalNextButton.Click += handler30;
        _detachViewHandlers.Add(() => RecordHorizontalNextButton.Click -= handler30);
        Microsoft.UI.Xaml.RoutedEventHandler handler31 = (sender, args) => Services.MusicUiContext.Invoke(() => VolumeButton_Click(sender, args));
        RecordHorizontalVolumeButton.Click += handler31;
        _detachViewHandlers.Add(() => RecordHorizontalVolumeButton.Click -= handler31);
        Microsoft.UI.Xaml.Input.PointerEventHandler handler32 = (sender, args) => Services.MusicUiContext.Invoke(() => InlineVolumePanel_PointerPressed(sender, args));
        InlineVolumePanel.PointerPressed += handler32;
        _detachViewHandlers.Add(() => InlineVolumePanel.PointerPressed -= handler32);
        Microsoft.UI.Xaml.Controls.Primitives.RangeBaseValueChangedEventHandler handler33 = (sender, args) => Services.MusicUiContext.Invoke(() => InlineSystemVolumeSlider_ValueChanged(sender, args));
        InlineSystemVolumeSlider.ValueChanged += handler33;
        _detachViewHandlers.Add(() => InlineSystemVolumeSlider.ValueChanged -= handler33);
    }
    private void DetachViewEvents()
    {
        foreach (var detach in _detachViewHandlers) detach();
        _detachViewHandlers.Clear();
    }
    private static T Require<T>(UserControl document, string name) where T : DependencyObject
    {
        object value = document.FindName(name);
        if (value is T typed) return typed;
        throw new InvalidOperationException($"Music XAML element '{name}' expected {typeof(T).FullName}, got {value?.GetType().FullName ?? "null"}.");
    }
}
